language: go
sudo: true

cache:
  directories:
    #- $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
    - $HOME/tmp

go:
    - 1.13.x

env:
  - OS=linux ARCH=amd64 TMP_DIR=$HOME/tmp

install: sudo make codecov.install gotestsum.install

before_script:
    - sudo /etc/init.d/postgresql stop
    - make postgres.start firestore.start postgres.scripts

script: make ci

# after_script: make postgres.kill firestore.kill

after_success: make codecov.push

notifications:
    email:
        on_success: change
        on_failure: always

services:
    - docker
