language: go
sudo: true

go:
    - 1.11.x

install: sudo make deps

before_script:
    - sudo /etc/init.d/postgresql stop
    - make postgres.run firestore.decodekeycontent

script: make ci

# after_script: make postgres.kill

after_success: make coverage.push

notifications:
    email:
        on_success: change
        on_failure: always

services:
    - docker
