language: go
sudo: true

go:
    - 1.11.x

install: sudo make deps

before_script: postgres.run

script: make ci

after_script: postgres.kill

after_success: make coverage.push

notifications:
    email:
        on_success: change
        on_failure: always

services:
    - docker
